[package]
name = "complex-grapher"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.68"
colors-transform = "0.2.11"
image = "0.24.5"
num-complex = "0.4.3"
